name: TransportationCamp
markdown: kramdown
permalink: /:year/:month/:title/
paginate: 5
paginate_path: archive/:num
baseurl: ""
exclude: [vendor, .idea]
plugins: [jekyll-paginate, jekyll-redirect-from]
